### ISSUE TITLE
Some feedback on the manual

### ISSUE THREAD

**Issue by fingolfin** [BNasmith/alco#14]
- Octonions are, as far as I know, non-associative. It would be good to point this explicitly in chapter 2
- indeed, I would even say that there should be a definition of octonions in this chapter, or at the very least a citation for a source where one can read a definition that closely matches the conventions used in your package
- the name `OctonionArithmetic` is quite irritating, it produces an algebra, but what is the "arithmetic" in this name supposed to indicate?
- in the descriptions for `Trace` and `Norm` it would be good to actually state how they are defined, not just some properties.
- many other manual entries are a bit short or incomplete; just stating some properties of the output but not enough to characterize it uniquely. E.g.
  - `IsLeechLatticeGramMatrix` docs state: "Specifically, this function confirms that the lattice defined by G is unimodular with shortest vectors of length at least 4." -- but this not "specific" at all, as it fails to mention that the input must be a 24x24 symmetric matrix
- in the docs for `RealPart` for quaternion it says "Using the built in GAP function [...]" which seems strange, why point that out
- ... and it then goes on to discuss GAP's `ImaginaryPart` which seems odd, why discuss that here? I am not saying it shouldn't but it should be clearer *why* it is discussed here-

**Comment by BNasmith** [comment]
I'll put some thought into this and do another edit. 

Regarding `OctonionArithmetic`, I suppose I'm using SCAlgebra objects to study octonion integer ring systems. In GAP, this is as simple as ensuring that all the coefficients in the given basis are integers (and that the structure constants are also integers). I notice that we can construct algebras in GAP over rings (like integers) and not just over fields. 

Regarding `ImaginaryPart`: the built in method for quaternions is counter-intuitive to me so I decided not to define a corresponding method for octonions because my definition would be inconsistent with the built in method for quaternions. I wanted package users to appreciate this complication but could rephrase.

**Comment by BNasmith** [comment]
I've done a careful edit of the manual chaps 1-4. I'll leave this issue open until I finish editing that last two chapters.

**Comment by BNasmith** [comment]
@fingolfin I have revised the entire manual on nearly every item to strive for better detail, accuracy, and clarity. If you have any other feedback I'm glad to hear it. If you are satisfied with the revised manual, could you close this issue?
